name: ShellCheck

on:
  push:
    paths:
      - 'install.sh'
  pull_request:
    paths:
      - 'install.sh'

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck
      - name: Run ShellCheck
        run: shellcheck install.sh 